import { useEffect, useState } from 'react';
import { api } from '../lib/api';
import type { HealthScoreResult, CashFlowForecastResponse } from '../lib/api';
import { Card, CardHeader, CardTitle, CardContent, CardDescription } from '../components/ui/card';
import { Button } from '../components/ui/button';
import { formatCurrency } from '../lib/utils';
import { Activity, Download, TrendingUp, TrendingDown, AlertTriangle, CheckCircle, Shield, Printer } from 'lucide-react';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, ReferenceLine } from 'recharts';

function gradeColor(grade: string): string {
  switch (grade) {
    case 'A': return 'text-green-600 dark:text-green-400';
    case 'B': return 'text-blue-600 dark:text-blue-400';
    case 'C': return 'text-yellow-600 dark:text-yellow-400';
    case 'D': return 'text-orange-600 dark:text-orange-400';
    default: return 'text-red-600 dark:text-red-400';
  }
}

function scoreBarColor(score: number, max: number): string {
  const pct = (score / max) * 100;
  if (pct >= 80) return 'bg-green-500';
  if (pct >= 60) return 'bg-blue-500';
  if (pct >= 40) return 'bg-yellow-500';
  return 'bg-red-500';
}

export function Reports() {
  const [health, setHealth] = useState<HealthScoreResult | null>(null);
  const [cashFlow, setCashFlow] = useState<CashFlowForecastResponse | null>(null);
  const [forecastDays, setForecastDays] = useState(90);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setLoading(true);
    Promise.all([api.getHealthScore(), api.getCashFlowForecast(forecastDays)])
      .then(([h, cf]) => { setHealth(h.healthScore); setCashFlow(cf); })
      .catch(console.error)
      .finally(() => setLoading(false));
  }, [forecastDays]);

  const handlePrint = () => {
    window.print();
  };

  const handleExportCSV = () => {
    if (!cashFlow) return;
    const headers = ['Date', 'Projected Balance', 'Income', 'Expenses', 'Label'];
    const rows = cashFlow.forecast.map(f => [f.date, f.projectedBalance, f.income, f.expenses, f.label || '']);
    const csv = [headers, ...rows].map(row => row.join(',')).join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `cash-flow-forecast-${new Date().toISOString().split('T')[0]}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (loading) return <div className="flex items-center justify-center h-64">Loading reports...</div>;

  const components = health ? Object.entries(health.components) : [];

  return (
    <div className="space-y-6 print:space-y-4">
      <div className="flex items-center justify-between print:hidden">
        <div>
          <h1 className="text-3xl font-bold">Reports</h1>
          <p className="text-[hsl(var(--muted-foreground))]">Financial health analysis and cash flow forecast</p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" onClick={handleExportCSV} disabled={!cashFlow}>
            <Download className="h-4 w-4 mr-2" />Export CSV
          </Button>
          <Button onClick={handlePrint}>
            <Printer className="h-4 w-4 mr-2" />Print Report
          </Button>
        </div>
      </div>

      {/* Print header */}
      <div className="hidden print:block">
        <h1 className="text-2xl font-bold">Financial Report — {new Date().toLocaleDateString()}</h1>
        <p className="text-gray-500">Generated by FinanceCmd</p>
      </div>

      {/* Health Score */}
      {health && (
        <>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <Card className="md:col-span-1">
              <CardContent className="p-6 flex flex-col items-center justify-center">
                <Shield className="h-10 w-10 text-[hsl(var(--muted-foreground))] mb-2" />
                <div className="text-6xl font-bold">{health.overallScore}</div>
                <div className={`text-3xl font-bold ${gradeColor(health.grade)}`}>Grade: {health.grade}</div>
                <p className="text-sm text-[hsl(var(--muted-foreground))] mt-1">Financial Health Score</p>
              </CardContent>
            </Card>

            <Card className="md:col-span-2">
              <CardHeader>
                <CardTitle className="text-lg flex items-center gap-2">
                  <Activity className="h-5 w-5" />Score Breakdown
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                {components.map(([key, comp]) => (
                  <div key={key}>
                    <div className="flex justify-between text-sm mb-1">
                      <span className="capitalize">{key.replace(/([A-Z])/g, ' $1').trim()}</span>
                      <span className="text-[hsl(var(--muted-foreground))]">{comp.label} — {comp.score}/20</span>
                    </div>
                    <div className="h-3 bg-[hsl(var(--muted))] rounded-full overflow-hidden">
                      <div
                        className={`h-full rounded-full transition-all ${scoreBarColor(comp.score, 20)}`}
                        style={{ width: `${(comp.score / 20) * 100}%` }}
                      />
                    </div>
                  </div>
                ))}
              </CardContent>
            </Card>
          </div>

          {/* Recommendations */}
          <Card>
            <CardHeader>
              <CardTitle className="text-lg">Recommendations</CardTitle>
              <CardDescription>Steps to improve your financial health</CardDescription>
            </CardHeader>
            <CardContent>
              <ul className="space-y-3">
                {health.recommendations.map((rec, i) => (
                  <li key={i} className="flex items-start gap-3">
                    {rec.includes('Excellent') ? (
                      <CheckCircle className="h-5 w-5 text-green-600 dark:text-green-400 mt-0.5 shrink-0" />
                    ) : (
                      <AlertTriangle className="h-5 w-5 text-yellow-600 dark:text-yellow-400 mt-0.5 shrink-0" />
                    )}
                    <span className="text-sm">{rec}</span>
                  </li>
                ))}
              </ul>
            </CardContent>
          </Card>
        </>
      )}

      {/* Cash Flow Forecast */}
      {cashFlow && (
        <>
          <Card>
            <CardHeader>
              <div className="flex items-center justify-between">
                <div>
                  <CardTitle className="text-lg">Cash Flow Forecast</CardTitle>
                  <CardDescription>Projected bank balance over time</CardDescription>
                </div>
                <div className="flex gap-2 print:hidden">
                  {[30, 60, 90].map(d => (
                    <Button key={d} variant={forecastDays === d ? 'default' : 'outline'} size="sm"
                      onClick={() => setForecastDays(d)}>
                      {d} days
                    </Button>
                  ))}
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
                <div className="text-center p-3 bg-[hsl(var(--muted))] rounded-lg">
                  <p className="text-xs text-[hsl(var(--muted-foreground))]">Current Balance</p>
                  <p className="text-lg font-bold">{formatCurrency(cashFlow.currentBalance)}</p>
                </div>
                <div className="text-center p-3 bg-[hsl(var(--muted))] rounded-lg">
                  <p className="text-xs text-[hsl(var(--muted-foreground))]">Min Projected</p>
                  <p className={`text-lg font-bold ${cashFlow.minimumProjectedBalance < 500 ? 'text-red-600 dark:text-red-400' : 'text-green-600 dark:text-green-400'}`}>
                    {formatCurrency(cashFlow.minimumProjectedBalance)}
                  </p>
                </div>
                <div className="text-center p-3 bg-[hsl(var(--muted))] rounded-lg">
                  <p className="text-xs text-[hsl(var(--muted-foreground))]">Recurring Income</p>
                  <p className="text-lg font-bold text-green-600 dark:text-green-400 flex items-center justify-center gap-1">
                    <TrendingUp className="h-4 w-4" />{cashFlow.recurringIncome.length} sources
                  </p>
                </div>
                <div className="text-center p-3 bg-[hsl(var(--muted))] rounded-lg">
                  <p className="text-xs text-[hsl(var(--muted-foreground))]">Recurring Expenses</p>
                  <p className="text-lg font-bold text-red-600 dark:text-red-400 flex items-center justify-center gap-1">
                    <TrendingDown className="h-4 w-4" />{cashFlow.recurringExpenses.length} bills
                  </p>
                </div>
              </div>

              {cashFlow.lowBalanceAlert && (
                <div className="mb-4 p-3 bg-red-50 dark:bg-red-950/30 border border-red-200 dark:border-red-800 rounded-lg flex items-center gap-2 text-red-700 dark:text-red-300">
                  <AlertTriangle className="h-5 w-5" />
                  <span className="text-sm font-medium">Low balance alert: Your projected balance drops below $500 during this period.</span>
                </div>
              )}

              <ResponsiveContainer width="100%" height={350}>
                <LineChart data={cashFlow.forecast}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="date" tickFormatter={(d: string) => {
                    const date = new Date(d);
                    return `${date.getMonth() + 1}/${date.getDate()}`;
                  }} interval={Math.floor(cashFlow.forecast.length / 8)} />
                  <YAxis tickFormatter={(v: number) => `$${(v / 1000).toFixed(0)}k`} />
                  <Tooltip formatter={(value: number | undefined) => formatCurrency(value ?? 0)}
                    labelFormatter={(label) => new Date(String(label)).toLocaleDateString()} />
                  <ReferenceLine y={500} stroke="#ef4444" strokeDasharray="5 5" label="$500 minimum" />
                  <Line type="monotone" dataKey="projectedBalance" stroke="#3b82f6" strokeWidth={2}
                    dot={false} name="Projected Balance" />
                </LineChart>
              </ResponsiveContainer>
            </CardContent>
          </Card>

          {/* Recurring items */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <Card>
              <CardHeader><CardTitle className="text-lg text-green-700 dark:text-green-400">Recurring Income</CardTitle></CardHeader>
              <CardContent>
                {cashFlow.recurringIncome.length === 0 ? (
                  <p className="text-sm text-[hsl(var(--muted-foreground))]">No recurring income detected. Mark transactions as recurring to enable forecasting.</p>
                ) : (
                  <ul className="space-y-2">
                    {cashFlow.recurringIncome.map((item: any, i: number) => (
                      <li key={i} className="flex justify-between items-center p-2 rounded bg-green-50 dark:bg-green-950/30">
                        <span className="text-sm font-medium">{item.description}</span>
                        <div className="text-right">
                          <span className="text-sm font-bold text-green-700 dark:text-green-300">{formatCurrency(item.amount)}</span>
                          <p className="text-xs text-[hsl(var(--muted-foreground))]">Day {item.dayOfMonth}</p>
                        </div>
                      </li>
                    ))}
                  </ul>
                )}
              </CardContent>
            </Card>
            <Card>
              <CardHeader><CardTitle className="text-lg text-red-700 dark:text-red-400">Recurring Expenses</CardTitle></CardHeader>
              <CardContent>
                {cashFlow.recurringExpenses.length === 0 ? (
                  <p className="text-sm text-[hsl(var(--muted-foreground))]">No recurring expenses detected. Mark transactions as recurring to enable forecasting.</p>
                ) : (
                  <ul className="space-y-2">
                    {cashFlow.recurringExpenses.map((item: any, i: number) => (
                      <li key={i} className="flex justify-between items-center p-2 rounded bg-red-50 dark:bg-red-950/30">
                        <span className="text-sm font-medium">{item.description}</span>
                        <div className="text-right">
                          <span className="text-sm font-bold text-red-700 dark:text-red-300">{formatCurrency(Math.abs(item.amount))}</span>
                          <p className="text-xs text-[hsl(var(--muted-foreground))]">Day {item.dayOfMonth}</p>
                        </div>
                      </li>
                    ))}
                  </ul>
                )}
              </CardContent>
            </Card>
          </div>
        </>
      )}
    </div>
  );
}
